FROM node:16-alpine

WORKDIR /app

# Atualize o npm para a versão mais recente
RUN npm install -g npm@latest

# Copie o arquivo de dependências
COPY package.json .

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .

# Exponha a porta que o Vite usa por padrão
EXPOSE 5173

# Comando para iniciar o Vite em modo de desenvolvimento
CMD ["npm", "run", "dev"]